# Generated by Django 5.2.17 on 2026-09-09 02:35

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0002_categoryattribute_variant_variantattributevalue_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("available_quantity", models.IntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "variant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_balance",
                        to="catalog.variant",
                    ),
                ),
            ],
            options={
                "db_table": "inventory_balances",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("available_quantity__gte", 0)),
                        name="inventory_nonnegative",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(max_length=80)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("ENTRY", "Entrada"),
                            ("SALE", "Venta"),
                            ("RETURN", "Devolución"),
                            ("CANCELLATION", "Cancelación"),
                            ("ADJUSTMENT", "Ajuste"),
                        ],
                        max_length=12,
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("previous_quantity", models.IntegerField()),
                ("resulting_quantity", models.IntegerField()),
                ("reason", models.CharField(max_length=1000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_movements",
                        to="catalog.variant",
                    ),
                ),
            ],
            options={
                "db_table": "stock_movements",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["variant", "-created_at", "-id"],
                        name="stock_movem_variant_f8fb54_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("previous_quantity__gte", 0),
                            ("resulting_quantity__gte", 0),
                        ),
                        name="movement_nonnegative_balances",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "resulting_quantity",
                                django.db.models.expressions.CombinedExpression(
                                    models.F("previous_quantity"),
                                    "+",
                                    models.F("quantity"),
                                ),
                            )
                        ),
                        name="movement_balances_match",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("quantity__gt", 0),
                                ("type__in", ["ENTRY", "RETURN", "CANCELLATION"]),
                            ),
                            models.Q(("quantity__lt", 0), ("type", "SALE")),
                            models.Q(
                                ("type", "ADJUSTMENT"),
                                models.Q(("quantity", 0), _negated=True),
                            ),
                            _connector="OR",
                        ),
                        name="movement_type_and_direction",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("reason", ""), _negated=True),
                        name="movement_reason_not_empty",
                    ),
                ],
            },
        ),
    ]
