# Generated by Codex on 2026-10-06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=60)),
                ("recipient_name", models.CharField(max_length=150)),
                ("phone", models.CharField(max_length=30)),
                ("address_line", models.CharField(max_length=240)),
                ("city", models.CharField(default="Pasto", max_length=80)),
                ("state", models.CharField(default="Nariño", max_length=80)),
                ("notes", models.CharField(blank=True, max_length=300)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "addresses",
                "ordering": ["-is_default", "-updated_at", "-id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=["user"], condition=models.Q(is_default=True),
                        name="address_one_default",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("label", ""), _negated=True),
                        name="address_label_not_empty",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("recipient_name", ""), _negated=True),
                        name="address_recipient_not_empty",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("phone", ""), _negated=True),
                        name="address_phone_not_empty",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("address_line", ""), _negated=True),
                        name="address_line_not_empty",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("city", ""), _negated=True),
                        name="address_city_not_empty",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("state", ""), _negated=True),
                        name="address_state_not_empty",
                    ),
                ],
            },
        ),
    ]
