# Generated by Django 5.2.17 on 2026-10-06 15:56

import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0002_categoryattribute_variant_variantattributevalue_and_more"),
        ("inventory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("idempotency_key", models.CharField(max_length=100)),
                ("request_hash", models.CharField(max_length=64)),
                ("status", models.CharField(default="PENDING", max_length=20)),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "discount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("shipping", models.DecimalField(decimal_places=2, max_digits=18)),
                ("total", models.DecimalField(decimal_places=2, max_digits=18)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "orders",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="OrderDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mode", models.CharField(max_length=10)),
                ("address", models.JSONField(default=dict)),
                ("cost", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="delivery",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "db_table": "order_deliveries",
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=180)),
                ("variant_name", models.CharField(max_length=120)),
                ("sku", models.CharField(max_length=80)),
                ("quantity", models.PositiveIntegerField()),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "discount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("total", models.DecimalField(decimal_places=2, max_digits=18)),
                ("promotion", models.JSONField(default=dict)),
                (
                    "movement",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.stockmovement",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="orders.order",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalog.variant",
                    ),
                ),
            ],
            options={
                "db_table": "order_items",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="OrderStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="history",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "db_table": "order_status_history",
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(default="PENDING", max_length=20)),
                ("report_deadline_at", models.DateTimeField()),
                ("review_deadline_at", models.DateTimeField(null=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "db_table": "payments",
            },
        ),
        migrations.CreateModel(
            name="PaymentStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="history",
                        to="orders.payment",
                    ),
                ),
            ],
            options={
                "db_table": "payment_status_history",
            },
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.UniqueConstraint(
                fields=("user", "idempotency_key"), name="order_user_key_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("discount__gte", 0),
                    ("shipping__gte", 0),
                    ("subtotal__gte", 0),
                    ("total__gte", 0),
                ),
                name="order_amounts_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "total",
                        django.db.models.expressions.CombinedExpression(
                            django.db.models.expressions.CombinedExpression(
                                models.F("subtotal"), "-", models.F("discount")
                            ),
                            "+",
                            models.F("shipping"),
                        ),
                    )
                ),
                name="order_total_matches",
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        ["PENDING", "PREPARING", "SHIPPED", "DELIVERED", "CANCELLED"],
                    )
                ),
                name="order_valid_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="orderdelivery",
            constraint=models.CheckConstraint(
                condition=models.Q(("cost__gte", 0)), name="delivery_cost_nonnegative"
            ),
        ),
        migrations.AddConstraint(
            model_name="orderdelivery",
            constraint=models.CheckConstraint(
                condition=models.Q(("mode__in", ["PICKUP", "URBAN", "SPECIAL"])),
                name="delivery_mode_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.UniqueConstraint(
                fields=("order", "variant"), name="order_variant_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("discount__gte", 0),
                    ("quantity__gt", 0),
                    ("total__gte", 0),
                    ("unit_price__gte", 0),
                ),
                name="order_item_values_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["PENDING", "REPORTED", "CONFIRMED", "REJECTED"])
                ),
                name="payment_valid_status",
            ),
        ),
    ]
