# Generated by Django 5.2.17 on 2026-10-06 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="reference",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="payment",
            name="reported_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "REPORTED"), _negated=True),
                    models.Q(
                        ("reported_at__isnull", False),
                        ("review_deadline_at__isnull", False),
                        ("review_deadline_at__gt", models.F("reported_at")),
                        models.Q(("reference", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="reported_payment_has_evidence_and_deadline",
            ),
        ),
    ]
