# Generated by Django 5.2.17 on 2026-09-09 01:59

import django.db.models.deletion
import django.db.models.functions.text
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=80)),
                ("name", models.CharField(max_length=120)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attributes",
                        to="catalog.category",
                    ),
                ),
            ],
            options={
                "db_table": "category_attributes",
                "ordering": ["name", "id"],
            },
        ),
        migrations.CreateModel(
            name="Variant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Estándar", max_length=120)),
                ("sku", models.CharField(max_length=80, unique=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="variants",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "db_table": "variants",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="VariantAttributeValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=500)),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="variant_values",
                        to="catalog.categoryattribute",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attribute_values",
                        to="catalog.variant",
                    ),
                ),
            ],
            options={
                "db_table": "variant_attribute_values",
                "ordering": ["attribute_id"],
            },
        ),
        migrations.AddConstraint(
            model_name="categoryattribute",
            constraint=models.UniqueConstraint(
                fields=("category", "code"), name="category_attribute_code_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="categoryattribute",
            constraint=models.CheckConstraint(
                condition=models.Q(("code", ""), _negated=True),
                name="attribute_code_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="categoryattribute",
            constraint=models.CheckConstraint(
                condition=models.Q(("name", ""), _negated=True),
                name="attribute_name_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="variant",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("sku"),
                name="variant_sku_ci_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="variant",
            constraint=models.CheckConstraint(
                condition=models.Q(("sku", ""), _negated=True),
                name="variant_sku_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="variant",
            constraint=models.CheckConstraint(
                condition=models.Q(("name", ""), _negated=True),
                name="variant_name_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="variant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("price__gte", 0), ("price__lte", Decimal("9999999999.99"))
                ),
                name="variant_price_valid_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="variantattributevalue",
            constraint=models.UniqueConstraint(
                fields=("variant", "attribute"), name="variant_attribute_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="variantattributevalue",
            constraint=models.CheckConstraint(
                condition=models.Q(("value", ""), _negated=True),
                name="variant_value_not_empty",
            ),
        ),
    ]
