# Generated by Django 5.2.17 on 2026-10-06 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0002_categoryattribute_variant_variantattributevalue_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Promotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                ("is_active", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "promotions",
                "ordering": ["id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("ends_at__gt", models.F("starts_at"))),
                        name="promotion_dates_valid",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PromotionVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "promotion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="promotions.promotion",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalog.variant",
                    ),
                ),
            ],
            options={
                "db_table": "promotion_variants",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("promotion", "variant"), name="promotion_variant_unique"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("price__gte", 0)),
                        name="promotion_price_nonnegative",
                    ),
                ],
            },
        ),
    ]
